version: '3.4'

services:
  kinderfoos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kinderfoos
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    ports:
      - 3000:3000
